#include"ls.c"
#include"pwd.c"
#include"rm.c"
#include"wc.c"
#include"mkdir.c"
#include"echo.c"
#include"mycd.c"
#include"cat.c"
#include"clear.c"
#include"help.c"
#include"date.c"
#include"rmdir.c"
#include "chmod.c"
#include "who.c"
#include "kill.c"
#include "exe.c"
